### ISSUE TITLE
storing of drafts vs final presentations/manuscripts

### ISSUE THREAD

**Issue by rachclark** [HBClab/ProjectTemplateStructure#4]
Just wondering about whether we want to make some decisions about whether drafts or just final documents for manuscripts/presentations get stored on the server. I've made many many presentations about various projects, but usually when the project is still on-going. Currently I have all of those on my own account. Would we want to store those on the server? what about manuscript drafts? or is that something we'd just store individually and then only save final versions on the server.

**Comment by jdkent** [comment]
I think presentations on the server would be a good idea (posters, slideshows, etc) since other people making presentations can use those as reference for their own presentations. 

As for drafts I like some form of version control, but Microsoft word doesn't provide an easy way of doing this. Perhaps a suggestion would be write what you can write for a session, then save the doc as "your_doc.v.01.docx" and increment the version after each writing session (e.g. once you open your_doc.v.01.docx, save it as your_doc.v.02.docx, then any changes will be associated with that newly named document). Then you may wish to delete older documents after a certain number of versions. What versions should be uploaded on the server probably will depend on how collaborative the writing is. The versioning system I just described is not easily amenable to multiple people working at the same time. I recommend reading the [git parable](http://tom.preston-werner.com/2009/05/19/the-git-parable.html) if you have time to learn about version control

**Comment by mwvoss** [comment]
I typically like writing in word and my system is to rename docs with major changes and then put all old docs with potentially useful information in a directory named archive.  

for both drafts and presentations we need to be sure they're named with some system that keeps the document order readable. something like lastname_date_topicORoutlet_v.XX.docx could help for single files or lastname_date_topicORoutlet for a directory

**Comment by jdkent** [comment]
I think this looks good. I'm going to close this issue for now, if there is more to say, I can reopen it.
