### ISSUE TITLE
create a BDAT folder

### ISSUE THREAD

**Issue by rachclark** [HBClab/ProjectTemplateStructure#6]
BDAT folder will store behavioral data in task folders. This should be within 3-Experiments at the same level as BIDS. Within that we'd have each task folder, in which we would like to have Data, Analysis, and Output directories. Tentatively, we'd have Pre and Post folders within Data, but we may change our minds on that.

**Comment by jdkent** [comment]
related to #3, but this is the preferred solution.
Would you be opposed to naming the raw data folder `sourcedata`, the analysis folder renamed into `derivatives`, just so that we can maintain some consistency for what types of data we can expect in these directory hierarchies? The below proposal borrows from [section 8.7 of the BIDS specification](http://bids.neuroimaging.io/bids_spec1.0.2.pdf) and this [google discussion](https://groups.google.com/forum/#!searchin/bids-discussion/behavioral$20events$20onsets%7Csort:date/bids-discussion/WFLT0YcoXNo/7Tef9UESAwAJ) (not yet a part of the official BIDS spec

For example, for a Simon Task, we would have the analyzable file:
1. This can contain all the subject's data for the simon task. 
`/Project/3-Experiments/BehData/Simon/task-simon_beh.tsv`

2. This file could describe the metadata (column names) of the csv, and some task context:
`/Project/3-Experiments/BehData/Simon/task-simon_beh.json`

3. This is the directory where raw (Eprime, psychopy, matlab, etc) data is stored (individual subject files and group aggregate):
`/Project/3-Experiments/BehData/Simon/sourcedata`

4. This is where analysis/playing with the data could go:
`/Project/3-Experiments/BehData/Simon/derivatives`
For example, you could have directory named CleanedData under derivatives where you filtered data based on some SD metrics or accuracy or what have you, and it could look like this:
`/Project/3-Experiments/BehData/Simon/derivatives/CleanedData/task-simon_cleaned.tsv`
with some other file like a README, and/or a R/jupyter notebook that does the cleaning and lists out the steps completed to do the cleaning.

(final) outputs, I would still recommend placing those in `/Project/3-Experiment/3-Outputs` (with some folder hierarchy mirroring the task data, for example:
`/Project/3-Experiment/3-Outputs/Simon/my_cool_figure.tiff`
`/Project/3-Experiment/3-Outputs/Simon/my_final_simon_notebook.tiff`
And non-final outputs would be inside the derivatives directory.

Finally, Having both BIDS and BehData suggests to me we should change 2-BIDS back to 2-Data (as per the [MRI folder organization](http://nikola.me/folder_structure.html), and have subfolders (BIDS and BehData)


Thoughts?

**Comment by mwvoss** [comment]
I like the structure proposed by James, and I like having these within a 2-Data directory, which allows for easy expansion of different types of data per project, like actigraphy data if want any local to the project and physiological data (fitness, saliva, blood). For all projects the primary forks would then be consistent but then directories more custom to the project under data makes sense.

**Comment by mwvoss** [comment]
i would say that under the sourcedata directory we store the raw data in whatever format is easiest based on the output of the program it was written in. this may involve pre and post sub-directories and/or sub-directories for individual subjects etc.  the file such as task-simon_beh.tsv would then be a summary file with multiple subjects right?

**Comment by jdkent** [comment]
Correct @mwvoss, that's how a summary file containing all the subject's data would be named under this scheme. I'm going to close this issue for now, but if there is more to say I can reopen it.
